<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Test.Shared</RootNamespace>
    <AssemblyName>Test.Shared</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Touchstone.Core" Version="0.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SerializationHelper\SerializationHelper.csproj" />
  </ItemGroup>

</Project>
